[packages]
    apt = ["git-gui", "pv", "tldr"]

    [[packages.dpkg]]
        cmd    = "gum"
        filter = ""
        name   = "gum"
        repo   = "charmbracelet/gum"
    [[packages.dpkg]]
        cmd    = "rg"
        filter = ""
        name   = "ripgrep"
        repo   = "BurntSushi/ripgrep"
    [[packages.dpkg]]
        cmd    = "bat"
        filter = "musl"
        name   = "bat"
        repo   = "sharkdp/bat"
    [[packages.dpkg]]
        cmd    = "fd"
        filter = "musl"
        name   = "fd"
        repo   = "sharkdp/fd"
