user_config:
  apt_upgrade: true
  install:
    apt: true
    dpkg: true
    pip: true
    fisher: true
    snap: true

  packages:
    apt:
      - fish
      - git-gui

    dpkg:
      - cmd: gum
        filter: ""
        name: gum
        repo: charmbracelet/gum
      - cmd: rg
        filter: ""
        name: ripgrep
        repo: BurntSushi/ripgrep
      - cmd: bat
        filter: musl
        name: bat
        repo: sharkdp/bat
      - cmd: fd
        filter: musl
        name: fd
        repo: sharkdp/fd

    pip:
      - tldr

    snap:
      - btop
      - gh

    fisher:
      - edc/bass
      - ilancosman/tide@v6
      - patrickf1/fzf.fish
