user_config:
  apt_upgrade: true
  install:
    apt: true
    dpkg: true
    pip: true
    fisher: true
    snap: false
    targz: true

  packages:
    apt:
      - name: fish
      - name: git-gui
      - name: ncdu
        hosttype: sandbox
      - name: ts-tool
        hosttype: sandbox

    dpkg:
      - name: gum
        cmd: gum
        filter: ""
        repo: charmbracelet/gum

      - name: ripgrep
        cmd: rg
        filter: ""
        repo: BurntSushi/ripgrep

      - name: bat
        cmd: bat
        filter: musl
        repo: sharkdp/bat

      - name: fd
        cmd: fd
        filter: musl
        repo: sharkdp/fd

      - name: delta
        cmd: delta
        filter: musl
        repo: dandavison/delta

    pip:
      - name: tldr
        hosttype: sandbox
      - name: thefuck

    snap:
      - name: btop
        hosttype: sandbox
      - name: gh
        hosttype: sandbox
      - name: neovim
        hosttype: sandbox

    fisher:
      - name: jorgebucaran/fisher
      - name: edc/bass
      - name: ilancosman/tide@v6
        hosttype: desktop

    targz:
      - name: lazygit
        cmd: lazygit
        filter: Linux
        repo: "jesseduffield/lazygit"
